/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_GENERATED_H
#define PCC_INCLUDED_GENERATED_H

#include "core.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct KeroParser_context_tag KeroParser_context_t;

KeroParser_context_t *KeroParser_create(KeroParserAuxil *auxil);
int KeroParser_parse(KeroParser_context_t *ctx, KeroObject **ret);
void KeroParser_destroy(KeroParser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_GENERATED_H */
