# Kero grammar
# This file is written in the "PackCC 1.8.0" grammar.

%prefix "KeroParser"

%value "KeroObject *"
%auxil "KeroParserAuxil *"

%header {
#include "core.h"
}

%source {
#include "generated_c_include.h"
}

Module <- _ EndOfFile

_ <- (Whitespace / Comment)*

Comment <- SingleLineComment
SingleLineComment <- '//' (!EndOfLine .)* (EndOfLine / EndOfFile)

Whitespace <- [ \t]
EndOfLine <- '\n' / '\r\n' / '\r'
EndOfFile <- !.
