repos:
  - repo: local
    hooks:
      - id: custom-script
        name: Run custom script before push
        entry: python scripts/dev.py pre-push
        language: python
        stages: [pre-push]
