[workspace]
members = [
    "crates/kero_lexer",
    "crates/kero_parser",
    "crates/kero_resolver",
    "crates/kero_trie",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
