#ifndef KERO_COMPILE_PARSER_NODE_KIND_GENERATED_H
#define KERO_COMPILE_PARSER_NODE_KIND_GENERATED_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum KCNodeKindTag {
  KCNodeKind_Module = 0,
  KCNodeKind_ModuleItemList,
  KCNodeKind_StatementList,
  KCNodeKind_IfStatement_IfElse,
  KCNodeKind_IfStatement_If,
  KCNodeKind_ArrayLiteral_Empty,
  KCNodeKind_ArrayLiteral_List,
  KCNodeKind_SpreadElement,
  KCNodeKind_ObjectLiteral_Empty,
  KCNodeKind_ObjectLiteral,
  KCNodeKind_PropertyDefinitionList,
  KCNodeKind_PropertyDefinition,
  KCNodeKind_CoverInitializedName,
  KCNodeKind_MemberExpression,
  KCNodeKind_NewExpression,
  KCNodeKind_CallExpression,
  KCNodeKind_Arguments_Empty,
  KCNodeKind_Arguments_Ellipsis,
  KCNodeKind_Arguments_List,
  KCNodeKind_Arguments_List_Ellipsis,
  KCNodeKind_PostfixExpression_PlusPlus,
  KCNodeKind_PostfixExpression_MinusMinus,
  KCNodeKind_UnaryExpression_PlusPlus,
  KCNodeKind_UnaryExpression_MinusMinus,
  KCNodeKind_UnaryExpression_Plus,
  KCNodeKind_UnaryExpression_Minus,
  KCNodeKind_UnaryExpression_Tilde,
  KCNodeKind_UnaryExpression_Bang,
  KCNodeKind_MultiplicativeExpression,
  KCNodeKind_MultiplicativeOperator_Asterisk,
  KCNodeKind_MultiplicativeOperator_Div,
  KCNodeKind_MultiplicativeOperator_Percent,
  KCNodeKind_AdditiveExpression_Plus,
  KCNodeKind_AdditiveExpression_Minus,
  KCNodeKind_ShiftExpression_LeftShift,
  KCNodeKind_ShiftExpression_RightShift,
  KCNodeKind_RelationalExpression_LessThan,
  KCNodeKind_RelationalExpression_GreaterThan,
  KCNodeKind_RelationalExpression_LessThanOrEqual,
  KCNodeKind_RelationalExpression_GreaterThanOrEqual,
  KCNodeKind_EqualityExpression_Equal,
  KCNodeKind_EqualityExpression_NotEqual,
  KCNodeKind_BitwiseANDExpression,
  KCNodeKind_BitwiseXORExpression,
  KCNodeKind_BitwiseORExpression,
  KCNodeKind_LogicalANDExpression,
  KCNodeKind_LogicalORExpression,
  KCNodeKind_ConditionalExpression,
  KCNodeKind_Expression,
  KCNodeKind_KW_Break,
  KCNodeKind_KW_Case,
  KCNodeKind_KW_Catch,
  KCNodeKind_KW_Class,
  KCNodeKind_KW_Const,
  KCNodeKind_KW_Continue,
  KCNodeKind_KW_Debugger,
  KCNodeKind_KW_Default,
  KCNodeKind_KW_Delete,
  KCNodeKind_KW_Do,
  KCNodeKind_KW_Else,
  KCNodeKind_KW_Export,
  KCNodeKind_KW_Extends,
  KCNodeKind_KW_Finally,
  KCNodeKind_KW_For,
  KCNodeKind_KW_Function,
  KCNodeKind_KW_If,
  KCNodeKind_KW_Import,
  KCNodeKind_KW_In,
  KCNodeKind_KW_Instanceof,
  KCNodeKind_KW_New,
  KCNodeKind_KW_Return,
  KCNodeKind_KW_Super,
  KCNodeKind_KW_Switch,
  KCNodeKind_KW_This,
  KCNodeKind_KW_Throw,
  KCNodeKind_KW_Try,
  KCNodeKind_KW_Typeof,
  KCNodeKind_KW_Var,
  KCNodeKind_KW_Void,
  KCNodeKind_KW_While,
  KCNodeKind_KW_With,
  KCNodeKind_KW_Yield,
  KCNodeKind_KW_Enum,
  KCNodeKind_KW_Await,
  KCNodeKind_KW_Implements,
  KCNodeKind_KW_Interface,
  KCNodeKind_KW_Package,
  KCNodeKind_KW_Private,
  KCNodeKind_KW_Protected,
  KCNodeKind_KW_Public,
  KCNodeKind_Block,
  KCNodeKind_BooleanLiteral_True,
  KCNodeKind_BooleanLiteral_False,
  KCNodeKind_NullLiteral,
} KCNodeKind;

const char *KCNodeKindToString(KCNodeKind Kind);

#ifdef __cplusplus
}
#endif

#endif // KERO_COMPILE_PARSER_NODE_KIND_GENERATED_H
