#include "NodeKindGenerated.h"

const char *KCNodeKindToString(KCNodeKind Kind) {
  switch (Kind) {
  case KCNodeKind_AdditiveExpression_Minus:
    return "AdditiveExpression_Minus";
  case KCNodeKind_AdditiveExpression_Plus:
    return "AdditiveExpression_Plus";
  case KCNodeKind_Arguments_Ellipsis:
    return "Arguments_Ellipsis";
  case KCNodeKind_Arguments_Empty:
    return "Arguments_Empty";
  case KCNodeKind_Arguments_List:
    return "Arguments_List";
  case KCNodeKind_Arguments_List_Ellipsis:
    return "Arguments_List_Ellipsis";
  case KCNodeKind_ArrayLiteral_Empty:
    return "ArrayLiteral_Empty";
  case KCNodeKind_ArrayLiteral_List:
    return "ArrayLiteral_List";
  case KCNodeKind_BitwiseANDExpression:
    return "BitwiseANDExpression";
  case KCNodeKind_BitwiseORExpression:
    return "BitwiseORExpression";
  case KCNodeKind_BitwiseXORExpression:
    return "BitwiseXORExpression";
  case KCNodeKind_Block:
    return "Block";
  case KCNodeKind_BooleanLiteral_False:
    return "BooleanLiteral_False";
  case KCNodeKind_BooleanLiteral_True:
    return "BooleanLiteral_True";
  case KCNodeKind_CallExpression:
    return "CallExpression";
  case KCNodeKind_ConditionalExpression:
    return "ConditionalExpression";
  case KCNodeKind_CoverInitializedName:
    return "CoverInitializedName";
  case KCNodeKind_DecimalDigit:
    return "DecimalDigit";
  case KCNodeKind_DecimalDigits:
    return "DecimalDigits";
  case KCNodeKind_DecimalIntegerLiteral:
    return "DecimalIntegerLiteral";
  case KCNodeKind_DecimalIntegerLiteral_Zero:
    return "DecimalIntegerLiteral_Zero";
  case KCNodeKind_DecimalLiteral_Integer:
    return "DecimalLiteral_Integer";
  case KCNodeKind_DecimalLiteral_Integer_Period:
    return "DecimalLiteral_Integer_Period";
  case KCNodeKind_DecimalLiteral_Period:
    return "DecimalLiteral_Period";
  case KCNodeKind_EqualityExpression_Equal:
    return "EqualityExpression_Equal";
  case KCNodeKind_EqualityExpression_NotEqual:
    return "EqualityExpression_NotEqual";
  case KCNodeKind_ExponentIndicator:
    return "ExponentIndicator";
  case KCNodeKind_ExponentPart:
    return "ExponentPart";
  case KCNodeKind_Expression:
    return "Expression";
  case KCNodeKind_IdentifierName:
    return "IdentifierName";
  case KCNodeKind_IdentifierPart:
    return "IdentifierPart";
  case KCNodeKind_IfStatement_If:
    return "IfStatement_If";
  case KCNodeKind_IfStatement_IfElse:
    return "IfStatement_IfElse";
  case KCNodeKind_KW_Await:
    return "KW_Await";
  case KCNodeKind_KW_Break:
    return "KW_Break";
  case KCNodeKind_KW_Case:
    return "KW_Case";
  case KCNodeKind_KW_Catch:
    return "KW_Catch";
  case KCNodeKind_KW_Class:
    return "KW_Class";
  case KCNodeKind_KW_Const:
    return "KW_Const";
  case KCNodeKind_KW_Continue:
    return "KW_Continue";
  case KCNodeKind_KW_Debugger:
    return "KW_Debugger";
  case KCNodeKind_KW_Default:
    return "KW_Default";
  case KCNodeKind_KW_Delete:
    return "KW_Delete";
  case KCNodeKind_KW_Do:
    return "KW_Do";
  case KCNodeKind_KW_Else:
    return "KW_Else";
  case KCNodeKind_KW_Enum:
    return "KW_Enum";
  case KCNodeKind_KW_Export:
    return "KW_Export";
  case KCNodeKind_KW_Extends:
    return "KW_Extends";
  case KCNodeKind_KW_Finally:
    return "KW_Finally";
  case KCNodeKind_KW_For:
    return "KW_For";
  case KCNodeKind_KW_Function:
    return "KW_Function";
  case KCNodeKind_KW_If:
    return "KW_If";
  case KCNodeKind_KW_Implements:
    return "KW_Implements";
  case KCNodeKind_KW_Import:
    return "KW_Import";
  case KCNodeKind_KW_In:
    return "KW_In";
  case KCNodeKind_KW_Instanceof:
    return "KW_Instanceof";
  case KCNodeKind_KW_Interface:
    return "KW_Interface";
  case KCNodeKind_KW_New:
    return "KW_New";
  case KCNodeKind_KW_Package:
    return "KW_Package";
  case KCNodeKind_KW_Private:
    return "KW_Private";
  case KCNodeKind_KW_Protected:
    return "KW_Protected";
  case KCNodeKind_KW_Public:
    return "KW_Public";
  case KCNodeKind_KW_Return:
    return "KW_Return";
  case KCNodeKind_KW_Super:
    return "KW_Super";
  case KCNodeKind_KW_Switch:
    return "KW_Switch";
  case KCNodeKind_KW_This:
    return "KW_This";
  case KCNodeKind_KW_Throw:
    return "KW_Throw";
  case KCNodeKind_KW_Try:
    return "KW_Try";
  case KCNodeKind_KW_Typeof:
    return "KW_Typeof";
  case KCNodeKind_KW_Var:
    return "KW_Var";
  case KCNodeKind_KW_Void:
    return "KW_Void";
  case KCNodeKind_KW_While:
    return "KW_While";
  case KCNodeKind_KW_With:
    return "KW_With";
  case KCNodeKind_KW_Yield:
    return "KW_Yield";
  case KCNodeKind_LogicalANDExpression:
    return "LogicalANDExpression";
  case KCNodeKind_LogicalORExpression:
    return "LogicalORExpression";
  case KCNodeKind_MemberExpression:
    return "MemberExpression";
  case KCNodeKind_Module:
    return "Module";
  case KCNodeKind_ModuleItemList:
    return "ModuleItemList";
  case KCNodeKind_MultiplicativeExpression:
    return "MultiplicativeExpression";
  case KCNodeKind_MultiplicativeOperator_Asterisk:
    return "MultiplicativeOperator_Asterisk";
  case KCNodeKind_MultiplicativeOperator_Div:
    return "MultiplicativeOperator_Div";
  case KCNodeKind_MultiplicativeOperator_Percent:
    return "MultiplicativeOperator_Percent";
  case KCNodeKind_NewExpression:
    return "NewExpression";
  case KCNodeKind_NonZeroDigit:
    return "NonZeroDigit";
  case KCNodeKind_NullLiteral:
    return "NullLiteral";
  case KCNodeKind_ObjectLiteral:
    return "ObjectLiteral";
  case KCNodeKind_ObjectLiteral_Empty:
    return "ObjectLiteral_Empty";
  case KCNodeKind_PostfixExpression_MinusMinus:
    return "PostfixExpression_MinusMinus";
  case KCNodeKind_PostfixExpression_PlusPlus:
    return "PostfixExpression_PlusPlus";
  case KCNodeKind_PropertyDefinition:
    return "PropertyDefinition";
  case KCNodeKind_PropertyDefinitionList:
    return "PropertyDefinitionList";
  case KCNodeKind_PT_ArrowFunction:
    return "PT_ArrowFunction";
  case KCNodeKind_PT_Assign:
    return "PT_Assign";
  case KCNodeKind_PT_Asterisk:
    return "PT_Asterisk";
  case KCNodeKind_PT_AsteriskAssign:
    return "PT_AsteriskAssign";
  case KCNodeKind_PT_Backslash:
    return "PT_Backslash";
  case KCNodeKind_PT_Bang:
    return "PT_Bang";
  case KCNodeKind_PT_BitwiseAND:
    return "PT_BitwiseAND";
  case KCNodeKind_PT_BitwiseANDAssign:
    return "PT_BitwiseANDAssign";
  case KCNodeKind_PT_BitwiseOR:
    return "PT_BitwiseOR";
  case KCNodeKind_PT_BitwiseORAssign:
    return "PT_BitwiseORAssign";
  case KCNodeKind_PT_BitwiseXOR:
    return "PT_BitwiseXOR";
  case KCNodeKind_PT_BitwiseXORAssign:
    return "PT_BitwiseXORAssign";
  case KCNodeKind_PT_Colon:
    return "PT_Colon";
  case KCNodeKind_PT_Comma:
    return "PT_Comma";
  case KCNodeKind_PT_Div:
    return "PT_Div";
  case KCNodeKind_PT_DivAssign:
    return "PT_DivAssign";
  case KCNodeKind_PT_Dollar:
    return "PT_Dollar";
  case KCNodeKind_PT_Ellipsis:
    return "PT_Ellipsis";
  case KCNodeKind_PT_Equal:
    return "PT_Equal";
  case KCNodeKind_PT_GreaterThan:
    return "PT_GreaterThan";
  case KCNodeKind_PT_GreaterThanOrEqual:
    return "PT_GreaterThanOrEqual";
  case KCNodeKind_PT_LeftBrace:
    return "PT_LeftBrace";
  case KCNodeKind_PT_LeftBracket:
    return "PT_LeftBracket";
  case KCNodeKind_PT_LeftParenthesis:
    return "PT_LeftParenthesis";
  case KCNodeKind_PT_LeftShift:
    return "PT_LeftShift";
  case KCNodeKind_PT_LeftShiftAssign:
    return "PT_LeftShiftAssign";
  case KCNodeKind_PT_LessThan:
    return "PT_LessThan";
  case KCNodeKind_PT_LessThanOrEqual:
    return "PT_LessThanOrEqual";
  case KCNodeKind_PT_LogicalAND:
    return "PT_LogicalAND";
  case KCNodeKind_PT_LogicalOR:
    return "PT_LogicalOR";
  case KCNodeKind_PT_Minus:
    return "PT_Minus";
  case KCNodeKind_PT_MinusAssign:
    return "PT_MinusAssign";
  case KCNodeKind_PT_MinusMinus:
    return "PT_MinusMinus";
  case KCNodeKind_PT_NotEqual:
    return "PT_NotEqual";
  case KCNodeKind_PT_NotStrictEqual:
    return "PT_NotStrictEqual";
  case KCNodeKind_PT_Percent:
    return "PT_Percent";
  case KCNodeKind_PT_PercentAssign:
    return "PT_PercentAssign";
  case KCNodeKind_PT_Period:
    return "PT_Period";
  case KCNodeKind_PT_Plus:
    return "PT_Plus";
  case KCNodeKind_PT_PlusAssign:
    return "PT_PlusAssign";
  case KCNodeKind_PT_PlusPlus:
    return "PT_PlusPlus";
  case KCNodeKind_PT_Question:
    return "PT_Question";
  case KCNodeKind_PT_RightBrace:
    return "PT_RightBrace";
  case KCNodeKind_PT_RightBracket:
    return "PT_RightBracket";
  case KCNodeKind_PT_RightParenthesis:
    return "PT_RightParenthesis";
  case KCNodeKind_PT_RightShift:
    return "PT_RightShift";
  case KCNodeKind_PT_RightShiftAssign:
    return "PT_RightShiftAssign";
  case KCNodeKind_PT_Semicolon:
    return "PT_Semicolon";
  case KCNodeKind_PT_StrictEqual:
    return "PT_StrictEqual";
  case KCNodeKind_PT_Tilde:
    return "PT_Tilde";
  case KCNodeKind_PT_Underscore:
    return "PT_Underscore";
  case KCNodeKind_PT_UnsignedRightShift:
    return "PT_UnsignedRightShift";
  case KCNodeKind_PT_UnsignedRightShiftAssign:
    return "PT_UnsignedRightShiftAssign";
  case KCNodeKind_RelationalExpression_GreaterThan:
    return "RelationalExpression_GreaterThan";
  case KCNodeKind_RelationalExpression_GreaterThanOrEqual:
    return "RelationalExpression_GreaterThanOrEqual";
  case KCNodeKind_RelationalExpression_LessThan:
    return "RelationalExpression_LessThan";
  case KCNodeKind_RelationalExpression_LessThanOrEqual:
    return "RelationalExpression_LessThanOrEqual";
  case KCNodeKind_ShiftExpression_LeftShift:
    return "ShiftExpression_LeftShift";
  case KCNodeKind_ShiftExpression_RightShift:
    return "ShiftExpression_RightShift";
  case KCNodeKind_SignedInteger_Minus:
    return "SignedInteger_Minus";
  case KCNodeKind_SignedInteger_Plus:
    return "SignedInteger_Plus";
  case KCNodeKind_SpreadElement:
    return "SpreadElement";
  case KCNodeKind_StatementList:
    return "StatementList";
  case KCNodeKind_UnaryExpression_Bang:
    return "UnaryExpression_Bang";
  case KCNodeKind_UnaryExpression_Minus:
    return "UnaryExpression_Minus";
  case KCNodeKind_UnaryExpression_MinusMinus:
    return "UnaryExpression_MinusMinus";
  case KCNodeKind_UnaryExpression_Plus:
    return "UnaryExpression_Plus";
  case KCNodeKind_UnaryExpression_PlusPlus:
    return "UnaryExpression_PlusPlus";
  case KCNodeKind_UnaryExpression_Tilde:
    return "UnaryExpression_Tilde";
  case KCNodeKind_UnicodeIDContinue:
    return "UnicodeIDContinue";
  case KCNodeKind_UnicodeIDStart:
    return "UnicodeIDStart";

  default:
    return "Unknown";
  }
}
