/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PARSERGENERATED_H
#define PCC_INCLUDED_PARSERGENERATED_H

#include "Core.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct KCParser_context_tag KCParser_context_t;

KCParser_context_t *KCParser_create(KCParserAuxil *auxil);
int KCParser_parse(KCParser_context_t *ctx, KCNodeId *ret);
void KCParser_destroy(KCParser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PARSERGENERATED_H */
