#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 108
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define PRODUCTION_ID_COUNT 30

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_if = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_else = 8,
  anon_sym_fn = 9,
  anon_sym_COLON = 10,
  anon_sym_COMMA = 11,
  anon_sym_DASH_GT = 12,
  anon_sym_bool = 13,
  sym_true = 14,
  sym_false = 15,
  sym_equal = 16,
  sym_not_equal = 17,
  sym_logical_and = 18,
  sym_logical_or = 19,
  sym_module = 20,
  sym__statement = 21,
  sym__expression_statement = 22,
  sym__expression = 23,
  sym_binary_expression = 24,
  sym__parenthesized_expression = 25,
  sym_if_statement = 26,
  sym__definition_statement = 27,
  sym_function_definition = 28,
  sym_type = 29,
  aux_sym_module_repeat1 = 30,
  aux_sym_function_definition_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_if] = "if",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [anon_sym_fn] = "fn",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_bool] = "bool",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_equal] = "equal",
  [sym_not_equal] = "not_equal",
  [sym_logical_and] = "logical_and",
  [sym_logical_or] = "logical_or",
  [sym_module] = "module",
  [sym__statement] = "_statement",
  [sym__expression_statement] = "_expression_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__parenthesized_expression] = "_parenthesized_expression",
  [sym_if_statement] = "if_statement",
  [sym__definition_statement] = "_definition_statement",
  [sym_function_definition] = "function_definition",
  [sym_type] = "type",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_bool] = anon_sym_bool,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_equal] = sym_equal,
  [sym_not_equal] = sym_not_equal,
  [sym_logical_and] = sym_logical_and,
  [sym_logical_or] = sym_logical_or,
  [sym_module] = sym_module,
  [sym__statement] = sym__statement,
  [sym__expression_statement] = sym__expression_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__parenthesized_expression] = sym__parenthesized_expression,
  [sym_if_statement] = sym_if_statement,
  [sym__definition_statement] = sym__definition_statement,
  [sym_function_definition] = sym_function_definition,
  [sym_type] = sym_type,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_not_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_and] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_or] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesized_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__definition_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_else_body = 1,
  field_else_if_statement = 2,
  field_function_body = 3,
  field_function_name = 4,
  field_if_body = 5,
  field_if_condition = 6,
  field_left = 7,
  field_operator = 8,
  field_return_type = 9,
  field_right = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_else_body] = "else_body",
  [field_else_if_statement] = "else_if_statement",
  [field_function_body] = "function_body",
  [field_function_name] = "function_name",
  [field_if_body] = "if_body",
  [field_if_condition] = "if_condition",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_return_type] = "return_type",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 1},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 2},
  [9] = {.index = 17, .length = 2},
  [10] = {.index = 19, .length = 4},
  [11] = {.index = 23, .length = 3},
  [12] = {.index = 26, .length = 2},
  [13] = {.index = 28, .length = 3},
  [14] = {.index = 31, .length = 3},
  [15] = {.index = 34, .length = 3},
  [16] = {.index = 37, .length = 4},
  [17] = {.index = 41, .length = 4},
  [18] = {.index = 45, .length = 4},
  [19] = {.index = 49, .length = 2},
  [20] = {.index = 51, .length = 5},
  [21] = {.index = 56, .length = 3},
  [22] = {.index = 59, .length = 2},
  [23] = {.index = 61, .length = 2},
  [24] = {.index = 63, .length = 3},
  [25] = {.index = 66, .length = 3},
  [26] = {.index = 69, .length = 2},
  [27] = {.index = 71, .length = 4},
  [28] = {.index = 75, .length = 3},
  [29] = {.index = 78, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [3] =
    {field_if_condition, 1},
  [4] =
    {field_if_body, 3},
    {field_if_condition, 1},
  [6] =
    {field_else_if_statement, 5},
    {field_if_condition, 1},
  [8] =
    {field_if_body, 3},
    {field_if_body, 4},
    {field_if_condition, 1},
  [11] =
    {field_function_name, 1},
  [12] =
    {field_else_if_statement, 6},
    {field_if_body, 3},
    {field_if_condition, 1},
  [15] =
    {field_function_body, 5},
    {field_function_name, 1},
  [17] =
    {field_else_body, 6},
    {field_if_condition, 1},
  [19] =
    {field_else_if_statement, 7},
    {field_if_body, 3},
    {field_if_body, 4},
    {field_if_condition, 1},
  [23] =
    {field_function_body, 5},
    {field_function_body, 6},
    {field_function_name, 1},
  [26] =
    {field_function_name, 1},
    {field_return_type, 5},
  [28] =
    {field_else_body, 6},
    {field_else_body, 7},
    {field_if_condition, 1},
  [31] =
    {field_else_body, 7},
    {field_if_body, 3},
    {field_if_condition, 1},
  [34] =
    {field_function_body, 7},
    {field_function_name, 1},
    {field_return_type, 5},
  [37] =
    {field_else_body, 7},
    {field_else_body, 8},
    {field_if_body, 3},
    {field_if_condition, 1},
  [41] =
    {field_else_body, 8},
    {field_if_body, 3},
    {field_if_body, 4},
    {field_if_condition, 1},
  [45] =
    {field_function_body, 7},
    {field_function_body, 8},
    {field_function_name, 1},
    {field_return_type, 5},
  [49] =
    {field_function_body, 8},
    {field_function_name, 1},
  [51] =
    {field_else_body, 8},
    {field_else_body, 9},
    {field_if_body, 3},
    {field_if_body, 4},
    {field_if_condition, 1},
  [56] =
    {field_function_body, 8},
    {field_function_body, 9},
    {field_function_name, 1},
  [59] =
    {field_function_name, 1},
    {field_return_type, 8},
  [61] =
    {field_function_body, 9},
    {field_function_name, 1},
  [63] =
    {field_function_body, 10},
    {field_function_name, 1},
    {field_return_type, 8},
  [66] =
    {field_function_body, 9},
    {field_function_body, 10},
    {field_function_name, 1},
  [69] =
    {field_function_name, 1},
    {field_return_type, 9},
  [71] =
    {field_function_body, 10},
    {field_function_body, 11},
    {field_function_name, 1},
    {field_return_type, 8},
  [75] =
    {field_function_body, 11},
    {field_function_name, 1},
    {field_return_type, 9},
  [78] =
    {field_function_body, 11},
    {field_function_body, 12},
    {field_function_name, 1},
    {field_return_type, 9},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '!', 2,
        '&', 1,
        '(', 8,
        ')', 9,
        ',', 13,
        '-', 4,
        ':', 12,
        ';', 7,
        '=', 3,
        '{', 10,
        '|', 5,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '|') ADVANCE(19);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_equal);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_not_equal);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_logical_and);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_logical_or);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_equal] = ACTIONS(1),
    [sym_not_equal] = ACTIONS(1),
    [sym_logical_and] = ACTIONS(1),
    [sym_logical_or] = ACTIONS(1),
  },
  [1] = {
    [sym_module] = STATE(103),
    [sym__statement] = STATE(87),
    [sym__expression_statement] = STATE(87),
    [sym__expression] = STATE(17),
    [sym_binary_expression] = STATE(17),
    [sym__parenthesized_expression] = STATE(17),
    [sym_if_statement] = STATE(87),
    [sym__definition_statement] = STATE(87),
    [sym_function_definition] = STATE(87),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [sym_true] = ACTIONS(5),
    [sym_false] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(72), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [30] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(46), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [60] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(57), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [90] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(43), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [120] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(66), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [150] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(41), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [180] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(82), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [210] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(76), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [240] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(62), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [270] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(31), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [300] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(5), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
    STATE(68), 5,
      sym__statement,
      sym__expression_statement,
      sym_if_statement,
      sym__definition_statement,
      sym_function_definition,
  [327] = 3,
    ACTIONS(37), 1,
      sym_logical_and,
    ACTIONS(35), 2,
      sym_equal,
      sym_not_equal,
    ACTIONS(33), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_logical_or,
  [343] = 2,
    ACTIONS(35), 2,
      sym_equal,
      sym_not_equal,
    ACTIONS(33), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_logical_and,
      sym_logical_or,
  [357] = 1,
    ACTIONS(33), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_equal,
      sym_not_equal,
      sym_logical_and,
      sym_logical_or,
  [369] = 1,
    ACTIONS(39), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_equal,
      sym_not_equal,
      sym_logical_and,
      sym_logical_or,
  [381] = 4,
    ACTIONS(37), 1,
      sym_logical_and,
    ACTIONS(43), 1,
      sym_logical_or,
    ACTIONS(35), 2,
      sym_equal,
      sym_not_equal,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [397] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(13), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
  [411] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(24), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
  [425] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(14), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
  [439] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(15), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
  [453] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 3,
      sym_identifier,
      sym_true,
      sym_false,
    STATE(23), 3,
      sym__expression,
      sym_binary_expression,
      sym__parenthesized_expression,
  [467] = 4,
    ACTIONS(37), 1,
      sym_logical_and,
    ACTIONS(43), 1,
      sym_logical_or,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 2,
      sym_equal,
      sym_not_equal,
  [481] = 4,
    ACTIONS(37), 1,
      sym_logical_and,
    ACTIONS(43), 1,
      sym_logical_or,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      sym_equal,
      sym_not_equal,
  [495] = 3,
    ACTIONS(61), 1,
      anon_sym_SEMI,
    STATE(25), 1,
      aux_sym_module_repeat1,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [506] = 2,
    ACTIONS(66), 1,
      anon_sym_else,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [515] = 2,
    ACTIONS(70), 1,
      anon_sym_else,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [524] = 2,
    ACTIONS(74), 1,
      anon_sym_else,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [533] = 1,
    ACTIONS(76), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [539] = 1,
    ACTIONS(78), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [545] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_module_repeat1,
  [555] = 1,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [561] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [571] = 3,
    ACTIONS(88), 1,
      anon_sym_if,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_if_statement,
  [581] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [591] = 1,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [597] = 1,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [603] = 1,
    ACTIONS(98), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [609] = 3,
    ACTIONS(88), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_if_statement,
  [619] = 1,
    ACTIONS(102), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [625] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_module_repeat1,
  [635] = 1,
    ACTIONS(106), 3,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
  [641] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_module_repeat1,
  [651] = 3,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_function_definition_repeat1,
  [661] = 1,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [667] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_module_repeat1,
  [677] = 1,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [683] = 3,
    ACTIONS(88), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_if_statement,
  [693] = 1,
    ACTIONS(122), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [699] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [709] = 1,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [715] = 1,
    ACTIONS(128), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [721] = 3,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_function_definition_repeat1,
  [731] = 1,
    ACTIONS(132), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [737] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [747] = 1,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [753] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_module_repeat1,
  [763] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [773] = 1,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [779] = 1,
    ACTIONS(144), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [785] = 1,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [791] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      aux_sym_module_repeat1,
  [801] = 1,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [807] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [817] = 1,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [823] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_module_repeat1,
  [833] = 3,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_function_definition_repeat1,
  [843] = 1,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [849] = 1,
    ACTIONS(163), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [855] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [865] = 1,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [871] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_module_repeat1,
  [881] = 1,
    ACTIONS(171), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [887] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [897] = 1,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [903] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      aux_sym_module_repeat1,
  [913] = 1,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [919] = 1,
    ACTIONS(181), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [925] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [935] = 1,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [941] = 1,
    ACTIONS(187), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [947] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_module_repeat1,
  [957] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [967] = 1,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [973] = 1,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [979] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_module_repeat1,
  [989] = 3,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    STATE(79), 1,
      aux_sym_module_repeat1,
  [999] = 1,
    ACTIONS(201), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1005] = 1,
    ACTIONS(203), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1010] = 2,
    ACTIONS(205), 1,
      anon_sym_bool,
    STATE(100), 1,
      sym_type,
  [1017] = 2,
    ACTIONS(205), 1,
      anon_sym_bool,
    STATE(89), 1,
      sym_type,
  [1024] = 2,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    ACTIONS(209), 1,
      anon_sym_DASH_GT,
  [1031] = 2,
    ACTIONS(205), 1,
      anon_sym_bool,
    STATE(101), 1,
      sym_type,
  [1038] = 2,
    ACTIONS(211), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
  [1045] = 2,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    ACTIONS(217), 1,
      anon_sym_DASH_GT,
  [1052] = 2,
    ACTIONS(205), 1,
      anon_sym_bool,
    STATE(44), 1,
      sym_type,
  [1059] = 2,
    ACTIONS(205), 1,
      anon_sym_bool,
    STATE(106), 1,
      sym_type,
  [1066] = 2,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      anon_sym_DASH_GT,
  [1073] = 1,
    ACTIONS(223), 1,
      anon_sym_LPAREN,
  [1077] = 1,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
  [1081] = 1,
    ACTIONS(227), 1,
      anon_sym_LBRACE,
  [1085] = 1,
    ACTIONS(229), 1,
      anon_sym_COLON,
  [1089] = 1,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
  [1093] = 1,
    ACTIONS(233), 1,
      sym_identifier,
  [1097] = 1,
    ACTIONS(235), 1,
      sym_identifier,
  [1101] = 1,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
  [1105] = 1,
    ACTIONS(239), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 150,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 270,
  [SMALL_STATE(12)] = 300,
  [SMALL_STATE(13)] = 327,
  [SMALL_STATE(14)] = 343,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 369,
  [SMALL_STATE(17)] = 381,
  [SMALL_STATE(18)] = 397,
  [SMALL_STATE(19)] = 411,
  [SMALL_STATE(20)] = 425,
  [SMALL_STATE(21)] = 439,
  [SMALL_STATE(22)] = 453,
  [SMALL_STATE(23)] = 467,
  [SMALL_STATE(24)] = 481,
  [SMALL_STATE(25)] = 495,
  [SMALL_STATE(26)] = 506,
  [SMALL_STATE(27)] = 515,
  [SMALL_STATE(28)] = 524,
  [SMALL_STATE(29)] = 533,
  [SMALL_STATE(30)] = 539,
  [SMALL_STATE(31)] = 545,
  [SMALL_STATE(32)] = 555,
  [SMALL_STATE(33)] = 561,
  [SMALL_STATE(34)] = 571,
  [SMALL_STATE(35)] = 581,
  [SMALL_STATE(36)] = 591,
  [SMALL_STATE(37)] = 597,
  [SMALL_STATE(38)] = 603,
  [SMALL_STATE(39)] = 609,
  [SMALL_STATE(40)] = 619,
  [SMALL_STATE(41)] = 625,
  [SMALL_STATE(42)] = 635,
  [SMALL_STATE(43)] = 641,
  [SMALL_STATE(44)] = 651,
  [SMALL_STATE(45)] = 661,
  [SMALL_STATE(46)] = 667,
  [SMALL_STATE(47)] = 677,
  [SMALL_STATE(48)] = 683,
  [SMALL_STATE(49)] = 693,
  [SMALL_STATE(50)] = 699,
  [SMALL_STATE(51)] = 709,
  [SMALL_STATE(52)] = 715,
  [SMALL_STATE(53)] = 721,
  [SMALL_STATE(54)] = 731,
  [SMALL_STATE(55)] = 737,
  [SMALL_STATE(56)] = 747,
  [SMALL_STATE(57)] = 753,
  [SMALL_STATE(58)] = 763,
  [SMALL_STATE(59)] = 773,
  [SMALL_STATE(60)] = 779,
  [SMALL_STATE(61)] = 785,
  [SMALL_STATE(62)] = 791,
  [SMALL_STATE(63)] = 801,
  [SMALL_STATE(64)] = 807,
  [SMALL_STATE(65)] = 817,
  [SMALL_STATE(66)] = 823,
  [SMALL_STATE(67)] = 833,
  [SMALL_STATE(68)] = 843,
  [SMALL_STATE(69)] = 849,
  [SMALL_STATE(70)] = 855,
  [SMALL_STATE(71)] = 865,
  [SMALL_STATE(72)] = 871,
  [SMALL_STATE(73)] = 881,
  [SMALL_STATE(74)] = 887,
  [SMALL_STATE(75)] = 897,
  [SMALL_STATE(76)] = 903,
  [SMALL_STATE(77)] = 913,
  [SMALL_STATE(78)] = 919,
  [SMALL_STATE(79)] = 925,
  [SMALL_STATE(80)] = 935,
  [SMALL_STATE(81)] = 941,
  [SMALL_STATE(82)] = 947,
  [SMALL_STATE(83)] = 957,
  [SMALL_STATE(84)] = 967,
  [SMALL_STATE(85)] = 973,
  [SMALL_STATE(86)] = 979,
  [SMALL_STATE(87)] = 989,
  [SMALL_STATE(88)] = 999,
  [SMALL_STATE(89)] = 1005,
  [SMALL_STATE(90)] = 1010,
  [SMALL_STATE(91)] = 1017,
  [SMALL_STATE(92)] = 1024,
  [SMALL_STATE(93)] = 1031,
  [SMALL_STATE(94)] = 1038,
  [SMALL_STATE(95)] = 1045,
  [SMALL_STATE(96)] = 1052,
  [SMALL_STATE(97)] = 1059,
  [SMALL_STATE(98)] = 1066,
  [SMALL_STATE(99)] = 1073,
  [SMALL_STATE(100)] = 1077,
  [SMALL_STATE(101)] = 1081,
  [SMALL_STATE(102)] = 1085,
  [SMALL_STATE(103)] = 1089,
  [SMALL_STATE(104)] = 1093,
  [SMALL_STATE(105)] = 1097,
  [SMALL_STATE(106)] = 1101,
  [SMALL_STATE(107)] = 1105,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_expression, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_statement, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 3),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 5),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 10, 0, 17),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 9, 0, 13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 14, 0, 29),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 13, 0, 28),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 13, 0, 27),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 6),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 7),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 12, 0, 26),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 12, 0, 25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, 0, 9),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, 0, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, 0, 10),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 11),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 12),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 12, 0, 24),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 11, 0, 23),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 9, 0, 14),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 9, 0, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 15),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 6),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 11, 0, 22),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 11, 0, 21),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 11, 0, 20),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 10, 0, 16),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, 0, 18),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, 0, 19),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, 0, 6),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 4, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [231] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kero(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
