/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_CORE_H
#define PCC_INCLUDED_CORE_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct KeroGrammarCore_context_tag KeroGrammarCore_context_t;

KeroGrammarCore_context_t *KeroGrammarCore_create(KeroParserAuxil *auxil);
int KeroGrammarCore_parse(KeroGrammarCore_context_t *ctx, void **ret);
void KeroGrammarCore_destroy(KeroGrammarCore_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_CORE_H */
