# Kero grammar
# This file is written in the "PackCC 1.8.0" grammar.

%prefix "KeroGrammarCore"

%value "void *" # Concreate type is kero::grammar::Node*
%auxil "void *" # Concreate type is kero::grammar::Parser*

%source {
#include "./bridge.h"
}

module <- _ end_of_file

_ <- (space / comment)*
comment <- "#" (!end_of_line .)* (end_of_line / end_of_file)
space <- [ \t] / end_of_line
end_of_line <- "\n" / "\r\n" / "\r"
end_of_file <- !.
