#ifndef KERO_GRAMMAR_NODE_KIND_GENERATED_H
#define KERO_GRAMMAR_NODE_KIND_GENERATED_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum KGNodeKindTag {
  KGNodeKind_Module = 0,
  KGNodeKind_ModuleItemList,
  KGNodeKind_StatementList,
  KGNodeKind_IfStatement_IfElse,
  KGNodeKind_IfStatement_If,
  KGNodeKind_ArrayLiteral_Empty,
  KGNodeKind_ArrayLiteral_List,
  KGNodeKind_SpreadElement,
  KGNodeKind_ObjectLiteral_Empty,
  KGNodeKind_ObjectLiteral,
  KGNodeKind_PropertyDefinitionList,
  KGNodeKind_PropertyDefinition,
  KGNodeKind_CoverInitializedName,
  KGNodeKind_MemberExpression,
  KGNodeKind_NewExpression,
  KGNodeKind_CallExpression,
  KGNodeKind_Arguments_Empty,
  KGNodeKind_Arguments_Ellipsis,
  KGNodeKind_Arguments_List,
  KGNodeKind_Arguments_List_Ellipsis,
  KGNodeKind_PostfixExpression_PlusPlus,
  KGNodeKind_PostfixExpression_MinusMinus,
  KGNodeKind_UnaryExpression_PlusPlus,
  KGNodeKind_UnaryExpression_MinusMinus,
  KGNodeKind_UnaryExpression_Plus,
  KGNodeKind_UnaryExpression_Minus,
  KGNodeKind_UnaryExpression_Tilde,
  KGNodeKind_UnaryExpression_Bang,
  KGNodeKind_MultiplicativeExpression,
  KGNodeKind_MultiplicativeOperator_Asterisk,
  KGNodeKind_MultiplicativeOperator_Div,
  KGNodeKind_MultiplicativeOperator_Percent,
  KGNodeKind_AdditiveExpression_Plus,
  KGNodeKind_AdditiveExpression_Minus,
  KGNodeKind_ShiftExpression_LeftShift,
  KGNodeKind_ShiftExpression_RightShift,
  KGNodeKind_RelationalExpression_LessThan,
  KGNodeKind_RelationalExpression_GreaterThan,
  KGNodeKind_RelationalExpression_LessThanOrEqual,
  KGNodeKind_RelationalExpression_GreaterThanOrEqual,
  KGNodeKind_EqualityExpression_Equal,
  KGNodeKind_EqualityExpression_NotEqual,
  KGNodeKind_BitwiseANDExpression,
  KGNodeKind_BitwiseXORExpression,
  KGNodeKind_BitwiseORExpression,
  KGNodeKind_LogicalANDExpression,
  KGNodeKind_LogicalORExpression,
  KGNodeKind_ConditionalExpression,
  KGNodeKind_Expression,
  KGNodeKind_KW_Break,
  KGNodeKind_KW_Case,
  KGNodeKind_KW_Catch,
  KGNodeKind_KW_Class,
  KGNodeKind_KW_Const,
  KGNodeKind_KW_Continue,
  KGNodeKind_KW_Debugger,
  KGNodeKind_KW_Default,
  KGNodeKind_KW_Delete,
  KGNodeKind_KW_Do,
  KGNodeKind_KW_Else,
  KGNodeKind_KW_Export,
  KGNodeKind_KW_Extends,
  KGNodeKind_KW_Finally,
  KGNodeKind_KW_For,
  KGNodeKind_KW_Function,
  KGNodeKind_KW_If,
  KGNodeKind_KW_Import,
  KGNodeKind_KW_In,
  KGNodeKind_KW_Instanceof,
  KGNodeKind_KW_New,
  KGNodeKind_KW_Return,
  KGNodeKind_KW_Super,
  KGNodeKind_KW_Switch,
  KGNodeKind_KW_This,
  KGNodeKind_KW_Throw,
  KGNodeKind_KW_Try,
  KGNodeKind_KW_Typeof,
  KGNodeKind_KW_Var,
  KGNodeKind_KW_Void,
  KGNodeKind_KW_While,
  KGNodeKind_KW_With,
  KGNodeKind_KW_Yield,
  KGNodeKind_KW_Enum,
  KGNodeKind_KW_Await,
  KGNodeKind_KW_Implements,
  KGNodeKind_KW_Interface,
  KGNodeKind_KW_Package,
  KGNodeKind_KW_Private,
  KGNodeKind_KW_Protected,
  KGNodeKind_KW_Public,
} KGNodeKind;

#ifdef __cplusplus
}
#endif

#endif // KERO_GRAMMAR_NODE_KIND_GENERATED_H
