/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PARSER_GENERATED_H
#define PCC_INCLUDED_PARSER_GENERATED_H

#include "parser_auxil.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct KGParser_context_tag KGParser_context_t;

KGParser_context_t *KGParser_create(KGParserAuxil *auxil);
int KGParser_parse(KGParser_context_t *ctx, KGNodeId *ret);
void KGParser_destroy(KGParser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PARSER_GENERATED_H */
